name: "Nueva tarea"
description: "Registro de una tarea que debe realizarse en el proyecto."
title: "[Task]: "
type: task
body:
  - type: dropdown
    id: priority
    attributes:
      label: "Prioridad"
      description: "Selecciona el nivel de prioridad de la tarea:"
      options:
        - "Alta"
        - "Media"
        - "Baja"
    validations:
      required: true

  - type: textarea
    id: task-summary
    attributes:
      label: "Detalles de la tarea"
      description: "Descripción de lo que se debe hacer, explicar qué pasos o acciones se deben realizar para completar la tarea."
      placeholder: "Actualizar la documentación del módulo X, 1. Revisar documentación actual\n2. Actualizar sección de API\n3. Enviar revisión para aprobación"
    validations:
      required: true
